import { describe, expect, it } from 'vitest'

import { buildFifoReport } from './fifo'
import type { NormalizedTransaction } from '../types'

const fifoSampleTransactions: NormalizedTransaction[] = [
  {
    id: 'buy-1',
    broker: 'shareworks',
    transactionType: 'ACQUIRE',
    grantName: 'Lot 1',
    grantNumber: 'L1',
    withdrawalReferenceNumber: 'buy-1',
    originatingReleaseReferenceNumber: 'buy-1',
    lotNumber: '1',
    tradeDate: '2025-02-01',
    acquisitionDate: '2025-02-01',
    shares: 10,
    pricePerShareUsd: 100,
    grossAmountUsd: 1000,
    feeUsd: 0,
    sourceRowNumber: 1,
  },
  {
    id: 'buy-2',
    broker: 'shareworks',
    transactionType: 'ACQUIRE',
    grantName: 'Lot 2',
    grantNumber: 'L2',
    withdrawalReferenceNumber: 'buy-2',
    originatingReleaseReferenceNumber: 'buy-2',
    lotNumber: '2',
    tradeDate: '2025-02-05',
    acquisitionDate: '2025-02-05',
    shares: 20,
    pricePerShareUsd: 110,
    grossAmountUsd: 2200,
    feeUsd: 0,
    sourceRowNumber: 2,
  },
  {
    id: 'sell-1',
    broker: 'shareworks',
    transactionType: 'SELL',
    grantName: 'Sale 1',
    grantNumber: 'S1',
    withdrawalReferenceNumber: 'sell-1',
    originatingReleaseReferenceNumber: 'sell-1',
    lotNumber: '1',
    tradeDate: '2025-02-07',
    acquisitionDate: '2025-02-01',
    shares: 3,
    pricePerShareUsd: 120,
    grossAmountUsd: 360,
    feeUsd: 3,
    sourceRowNumber: 7,
  },
  {
    id: 'sell-2',
    broker: 'shareworks',
    transactionType: 'SELL',
    grantName: 'Sale 2',
    grantNumber: 'S2',
    withdrawalReferenceNumber: 'sell-2',
    originatingReleaseReferenceNumber: 'sell-2',
    lotNumber: '1',
    tradeDate: '2025-02-08',
    acquisitionDate: '2025-02-01',
    shares: 4,
    pricePerShareUsd: 121,
    grossAmountUsd: 484,
    feeUsd: 4,
    sourceRowNumber: 8,
  },
  {
    id: 'sell-3',
    broker: 'shareworks',
    transactionType: 'SELL',
    grantName: 'Sale 3',
    grantNumber: 'S3',
    withdrawalReferenceNumber: 'sell-3',
    originatingReleaseReferenceNumber: 'sell-3',
    lotNumber: '1',
    tradeDate: '2025-02-09',
    acquisitionDate: '2025-02-01',
    shares: 5,
    pricePerShareUsd: 122,
    grossAmountUsd: 610,
    feeUsd: 5,
    sourceRowNumber: 9,
  },
  {
    id: 'sell-4',
    broker: 'shareworks',
    transactionType: 'SELL',
    grantName: 'Sale 4',
    grantNumber: 'S4',
    withdrawalReferenceNumber: 'sell-4',
    originatingReleaseReferenceNumber: 'sell-4',
    lotNumber: '2',
    tradeDate: '2025-02-10',
    acquisitionDate: '2025-02-05',
    shares: 6,
    pricePerShareUsd: 123,
    grossAmountUsd: 738,
    feeUsd: 6,
    sourceRowNumber: 10,
  },
  {
    id: 'sell-5',
    broker: 'shareworks',
    transactionType: 'SELL',
    grantName: 'Sale 5',
    grantNumber: 'S5',
    withdrawalReferenceNumber: 'sell-5',
    originatingReleaseReferenceNumber: 'sell-5',
    lotNumber: '2',
    tradeDate: '2025-02-11',
    acquisitionDate: '2025-02-05',
    shares: 7,
    pricePerShareUsd: 124,
    grossAmountUsd: 868,
    feeUsd: 7,
    sourceRowNumber: 11,
  },
]

describe('buildFifoReport', () => {
  it('splits acquisition lots across sell transactions using FIFO order', () => {
    const report = buildFifoReport(fifoSampleTransactions)

    expect(report.matchedLots).toHaveLength(6)
    expect(report.matchedLots.map((lot) => [lot.buyDate, lot.sellDate, lot.sharesMatched])).toEqual([
      ['2025-02-01', '2025-02-07', 3],
      ['2025-02-01', '2025-02-08', 4],
      ['2025-02-01', '2025-02-09', 3],
      ['2025-02-05', '2025-02-09', 2],
      ['2025-02-05', '2025-02-10', 6],
      ['2025-02-05', '2025-02-11', 7],
    ])
    expect(report.openHoldings).toEqual([
      {
        id: 'buy-2-open',
        grantName: 'Lot 2',
        grantNumber: 'L2',
        buyDate: '2025-02-05',
        sourceRowNumber: 2,
        sharesRemaining: 5,
        buyPricePerShareUsd: 110,
        costBasisUsd: 550,
      },
    ])
    expect(report.unmatchedSellShares).toBe(0)
  })
})
