import { describe, expect, it } from 'vitest'

import { buildFifoReport } from './fifo'
import type { NormalizedTransaction } from '../types'

const fifoSampleTransactions: NormalizedTransaction[] = [
  {
    id: 'buy-1',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'ACQUIRE',
    grantName: 'Lot 1',
    grantNumber: 'L1',
    withdrawalReferenceNumber: 'buy-1',
    originatingReleaseReferenceNumber: 'buy-1',
    lotNumber: '1',
    tradeDate: '2025-02-01',
    acquisitionDate: '2025-02-01',
    shares: 10,
    pricePerShareUsd: 100,
    grossAmountUsd: 1000,
    feeUsd: 0,
    sourceRowNumber: 1,
  },
  {
    id: 'buy-2',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'ACQUIRE',
    grantName: 'Lot 2',
    grantNumber: 'L2',
    withdrawalReferenceNumber: 'buy-2',
    originatingReleaseReferenceNumber: 'buy-2',
    lotNumber: '2',
    tradeDate: '2025-02-05',
    acquisitionDate: '2025-02-05',
    shares: 20,
    pricePerShareUsd: 110,
    grossAmountUsd: 2200,
    feeUsd: 0,
    sourceRowNumber: 2,
  },
  {
    id: 'sell-1',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'SELL',
    grantName: 'Sale 1',
    grantNumber: 'S1',
    withdrawalReferenceNumber: 'sell-1',
    originatingReleaseReferenceNumber: 'sell-1',
    lotNumber: '1',
    tradeDate: '2025-02-07',
    acquisitionDate: '2025-02-01',
    shares: 3,
    pricePerShareUsd: 120,
    grossAmountUsd: 360,
    feeUsd: 3,
    sourceRowNumber: 7,
  },
  {
    id: 'sell-2',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'SELL',
    grantName: 'Sale 2',
    grantNumber: 'S2',
    withdrawalReferenceNumber: 'sell-2',
    originatingReleaseReferenceNumber: 'sell-2',
    lotNumber: '1',
    tradeDate: '2025-02-08',
    acquisitionDate: '2025-02-01',
    shares: 4,
    pricePerShareUsd: 121,
    grossAmountUsd: 484,
    feeUsd: 4,
    sourceRowNumber: 8,
  },
  {
    id: 'sell-3',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'SELL',
    grantName: 'Sale 3',
    grantNumber: 'S3',
    withdrawalReferenceNumber: 'sell-3',
    originatingReleaseReferenceNumber: 'sell-3',
    lotNumber: '1',
    tradeDate: '2025-02-09',
    acquisitionDate: '2025-02-01',
    shares: 5,
    pricePerShareUsd: 122,
    grossAmountUsd: 610,
    feeUsd: 5,
    sourceRowNumber: 9,
  },
  {
    id: 'sell-4',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'SELL',
    grantName: 'Sale 4',
    grantNumber: 'S4',
    withdrawalReferenceNumber: 'sell-4',
    originatingReleaseReferenceNumber: 'sell-4',
    lotNumber: '2',
    tradeDate: '2025-02-10',
    acquisitionDate: '2025-02-05',
    shares: 6,
    pricePerShareUsd: 123,
    grossAmountUsd: 738,
    feeUsd: 6,
    sourceRowNumber: 10,
  },
  {
    id: 'sell-5',
    broker: 'shareworks',
    stockSymbol: 'TEAM',
    transactionType: 'SELL',
    grantName: 'Sale 5',
    grantNumber: 'S5',
    withdrawalReferenceNumber: 'sell-5',
    originatingReleaseReferenceNumber: 'sell-5',
    lotNumber: '2',
    tradeDate: '2025-02-11',
    acquisitionDate: '2025-02-05',
    shares: 7,
    pricePerShareUsd: 124,
    grossAmountUsd: 868,
    feeUsd: 7,
    sourceRowNumber: 11,
  },
]

describe('buildFifoReport', () => {
  it('splits acquisition lots across sell transactions using FIFO order', () => {
    const report = buildFifoReport(fifoSampleTransactions)

    expect(report.matchedLots).toHaveLength(6)
    expect(report.matchedLots.map((lot) => [lot.buyDate, lot.sellDate, lot.sharesMatched])).toEqual([
      ['2025-02-01', '2025-02-07', 3],
      ['2025-02-01', '2025-02-08', 4],
      ['2025-02-01', '2025-02-09', 3],
      ['2025-02-05', '2025-02-09', 2],
      ['2025-02-05', '2025-02-10', 6],
      ['2025-02-05', '2025-02-11', 7],
    ])
    expect(report.openHoldings).toEqual([
      {
        id: 'buy-2-open',
        stockSymbol: 'TEAM',
        grantName: 'Lot 2',
        grantNumber: 'L2',
        buyDate: '2025-02-05',
        sourceRowNumber: 2,
        sharesRemaining: 5,
        buyPricePerShareUsd: 110,
        costBasisUsd: 550,
      },
    ])
    expect(report.unmatchedSellShares).toBe(0)
  })

  it('uses source-row order for same-day lots and tracks unmatched sell shares', () => {
    const report = buildFifoReport([
      {
        id: 'buy-later-row',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'ACQUIRE',
        grantName: 'Later row',
        grantNumber: 'L2',
        withdrawalReferenceNumber: 'buy-later-row',
        originatingReleaseReferenceNumber: 'buy-later-row',
        lotNumber: '2',
        tradeDate: '2025-04-01',
        acquisitionDate: '2025-04-01',
        shares: 1,
        pricePerShareUsd: 200,
        grossAmountUsd: 200,
        feeUsd: 0,
        sourceRowNumber: 9,
      },
      {
        id: 'buy-earlier-row',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'ACQUIRE',
        grantName: 'Earlier row',
        grantNumber: 'L1',
        withdrawalReferenceNumber: 'buy-earlier-row',
        originatingReleaseReferenceNumber: 'buy-earlier-row',
        lotNumber: '1',
        tradeDate: '2025-04-01',
        acquisitionDate: '2025-04-01',
        shares: 1,
        pricePerShareUsd: 100,
        grossAmountUsd: 100,
        feeUsd: 0,
        sourceRowNumber: 2,
      },
      {
        id: 'sell-same-day',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'SELL',
        grantName: 'Sale',
        grantNumber: 'S1',
        withdrawalReferenceNumber: 'sell-same-day',
        originatingReleaseReferenceNumber: 'sell-same-day',
        lotNumber: '3',
        tradeDate: '2025-04-02',
        acquisitionDate: '2025-04-02',
        shares: 3,
        pricePerShareUsd: 150,
        grossAmountUsd: 450,
        feeUsd: 1,
        sourceRowNumber: 10,
      },
    ])

    expect(report.matchedLots).toEqual([
      expect.objectContaining({
        acquisitionTransactionId: 'buy-earlier-row',
        sharesMatched: 1,
        buyAmountUsd: 100,
        allocatedFeeUsd: 0.33,
      }),
      expect.objectContaining({
        acquisitionTransactionId: 'buy-later-row',
        sharesMatched: 1,
        buyAmountUsd: 200,
        allocatedFeeUsd: 0.33,
      }),
    ])
    expect(report.openHoldings).toEqual([])
    expect(report.unmatchedSellShares).toBe(1)
  })

  it('sorts reverse-ordered trades by date, keeps symbols separate, and supports fractional shares', () => {
    const report = buildFifoReport([
      {
        id: 'sell-goog',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'SELL',
        grantName: 'GOOG',
        grantNumber: 'GOOG',
        withdrawalReferenceNumber: 'sell-goog',
        originatingReleaseReferenceNumber: 'sell-goog',
        lotNumber: '4',
        tradeDate: '2025-04-10',
        acquisitionDate: '2025-04-10',
        shares: 1.25,
        pricePerShareUsd: 150,
        grossAmountUsd: 187.5,
        feeUsd: 0.5,
        sourceRowNumber: 4,
      },
      {
        id: 'sell-msft',
        broker: 'ibkr',
        stockSymbol: 'MSFT',
        transactionType: 'SELL',
        grantName: 'MSFT',
        grantNumber: 'MSFT',
        withdrawalReferenceNumber: 'sell-msft',
        originatingReleaseReferenceNumber: 'sell-msft',
        lotNumber: '3',
        tradeDate: '2025-04-07',
        acquisitionDate: '2025-04-07',
        shares: 2.5,
        pricePerShareUsd: 310,
        grossAmountUsd: 775,
        feeUsd: 0.25,
        sourceRowNumber: 3,
      },
      {
        id: 'buy-msft',
        broker: 'ibkr',
        stockSymbol: 'MSFT',
        transactionType: 'ACQUIRE',
        grantName: 'MSFT',
        grantNumber: 'MSFT',
        withdrawalReferenceNumber: 'buy-msft',
        originatingReleaseReferenceNumber: 'buy-msft',
        lotNumber: '2',
        tradeDate: '2025-04-02',
        acquisitionDate: '2025-04-02',
        shares: 5,
        pricePerShareUsd: 300,
        grossAmountUsd: 1500,
        feeUsd: 0,
        sourceRowNumber: 2,
      },
      {
        id: 'buy-goog-2',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'ACQUIRE',
        grantName: 'GOOG',
        grantNumber: 'GOOG',
        withdrawalReferenceNumber: 'buy-goog-2',
        originatingReleaseReferenceNumber: 'buy-goog-2',
        lotNumber: '5',
        tradeDate: '2025-04-05',
        acquisitionDate: '2025-04-05',
        shares: 1,
        pricePerShareUsd: 125,
        grossAmountUsd: 125,
        feeUsd: 0,
        sourceRowNumber: 5,
      },
      {
        id: 'buy-goog-1',
        broker: 'ibkr',
        stockSymbol: 'GOOG',
        transactionType: 'ACQUIRE',
        grantName: 'GOOG',
        grantNumber: 'GOOG',
        withdrawalReferenceNumber: 'buy-goog-1',
        originatingReleaseReferenceNumber: 'buy-goog-1',
        lotNumber: '1',
        tradeDate: '2025-04-01',
        acquisitionDate: '2025-04-01',
        shares: 1,
        pricePerShareUsd: 100,
        grossAmountUsd: 100,
        feeUsd: 0,
        sourceRowNumber: 1,
      },
    ])

    expect(report.matchedLots.map((lot) => ({
      stockSymbol: lot.stockSymbol,
      buyDate: lot.buyDate,
      sellDate: lot.sellDate,
      sharesMatched: lot.sharesMatched,
      allocatedFeeUsd: lot.allocatedFeeUsd,
    }))).toEqual([
      {
        stockSymbol: 'MSFT',
        buyDate: '2025-04-02',
        sellDate: '2025-04-07',
        sharesMatched: 2.5,
        allocatedFeeUsd: 0.25,
      },
      {
        stockSymbol: 'GOOG',
        buyDate: '2025-04-01',
        sellDate: '2025-04-10',
        sharesMatched: 1,
        allocatedFeeUsd: 0.4,
      },
      {
        stockSymbol: 'GOOG',
        buyDate: '2025-04-05',
        sellDate: '2025-04-10',
        sharesMatched: 0.25,
        allocatedFeeUsd: 0.1,
      },
    ])
    expect(report.openHoldings).toEqual([
      {
        id: 'buy-msft-open',
        stockSymbol: 'MSFT',
        grantName: 'MSFT',
        grantNumber: 'MSFT',
        buyDate: '2025-04-02',
        sourceRowNumber: 2,
        sharesRemaining: 2.5,
        buyPricePerShareUsd: 300,
        costBasisUsd: 750,
      },
      {
        id: 'buy-goog-2-open',
        stockSymbol: 'GOOG',
        grantName: 'GOOG',
        grantNumber: 'GOOG',
        buyDate: '2025-04-05',
        sourceRowNumber: 5,
        sharesRemaining: 0.75,
        buyPricePerShareUsd: 125,
        costBasisUsd: 93.75,
      },
    ])
    expect(report.unmatchedSellShares).toBe(0)
  })
})
